---
apiVersion: dcim.netbox.upbound.io/v1alpha1
kind: Site
metadata:
  name: testsite
spec:
  forProvider:
    description: production
    facility: prod-colo
    status: active
    tags:
      - new
      - test
---
apiVersion: virtualization.netbox.upbound.io/v1alpha1
kind: Machine
metadata: 
  name: testmachine
spec:
  forProvider: 
    siteIdRef:
      name: testsite