apiVersion: device.netbox.upbound.io/v1alpha1
kind: DeviceType
metadata: {}
spec:
  deletionPolicy: string
  forProvider:
    manufacturerId: number
    model: string
    partNumber: string
    slug: string
    tags: ["string"]
    uHeight: number
  managementPolicy: string
  providerConfigRef:
    name: string
    policy:
      resolution: string
      resolve: string
  providerRef:
    name: string
    policy:
      resolution: string
      resolve: string
  publishConnectionDetailsTo:
    configRef:
      name: string
      policy:
        resolution: string
        resolve: string
    metadata:
      annotations:
      labels:
      type: string
    name: string
  writeConnectionSecretToRef:
    name: string
    namespace: string
status:
  atProvider:
    id: string
    manufacturerId: number
    model: string
    partNumber: string
    slug: string
    tags: ["string"]
    uHeight: number
  conditions:
  - lastTransitionTime: string
    message: string
    reason: string
    status: string
    type: string
