apiVersion: netbox.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
  namespace: upbound-system
spec:
  credentials:
    source: Secret
    secretRef:
      name: example-creds
      namespace: upbound-system
      key: credentials
