apiVersion: netbox.netbox.upbound.io/v1alpha1
kind: Device
metadata:
  name: test-device
spec:
  deletionPolicy: Delete
  forProvider:
    comments: "this is a test"
    deviceTypeId: 2
    roleId: 1
    serial: MYSERIAL
    siteId: 1
    status: active
    tags: 
      - leaf
      - tor
    tenantId: 1
    comments: "this is a test-device"
  providerConfigRef:
    name: default