---
apiVersion: tenant.netbox.upbound.io/v1alpha1
kind: Tenant
metadata: 
  name: testtenant
spec:
  forProvider:
    slug: testtenant
---
apiVersion: ipam.netbox.upbound.io/v1alpha1
kind: Target
metadata: 
  name: testtarget-on-ids
spec:
  forProvider:
    description: test
    tags: 
      - test
      - prefix
      - id
---
apiVersion: ipam.netbox.upbound.io/v1alpha1
kind: Target
metadata: 
  name: testtarget-with-ids
spec:
  forProvider:
    description: test
    tags: 
      - test
      - prefix
      - id
    tenantIdRef:
      name: testtenant